comment "Remove existing items";
removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;

comment "Add containers";
this forceAddUniform "rhs_uniform_cu_ucp";
for "_i" from 1 to 10 do {this addItemToUniform "ACE_packingBandage";};
for "_i" from 1 to 10 do {this addItemToUniform "ACE_elasticBandage";};
for "_i" from 1 to 2 do {this addItemToUniform "ACE_tourniquet";};
for "_i" from 1 to 5 do {this addItemToUniform "ACE_morphine";};
for "_i" from 1 to 7 do {this addItemToUniform "ACE_atropine";};
this addItemToUniform "ACE_epinephrine";
this addItemToUniform "ACE_EarPlugs";
this addItemToUniform "ACE_Kestrel4500";
this addItemToUniform "ACE_CableTie";
this addVest "rhsusf_iotv_ucp_Squadleader";
this addItemToVest "ACE_DAGR";
this addItemToVest "ACE_RangeCard";
this addItemToVest "ACE_ATragMX";
this addItemToVest "ACE_RangeTable_82mm";
this addItemToVest "ACE_MapTools";
for "_i" from 1 to 9 do {this addItemToVest "rhsusf_20Rnd_762x51_m993_Mag";};
for "_i" from 1 to 2 do {this addItemToVest "HandGrenade";};
this addItemToVest "SmokeShell";
this addBackpack "rhsusf_assault_eagleaiii_ucp";
this addItemToBackpack "16Rnd_9x21_Mag";
for "_i" from 1 to 9 do {this addItemToBackpack "rhsusf_20Rnd_762x51_m993_Mag";};
for "_i" from 1 to 2 do {this addItemToBackpack "SmokeShell";};
for "_i" from 1 to 3 do {this addItemToBackpack "SmokeShellGreen";};
this addHeadgear "rhsusf_ach_helmet_headset_ucp";
this addGoggles "rhs_googles_clear";

comment "Add weapons";
this addWeapon "rhs_weap_m14ebrri";
this addPrimaryWeaponItem "rhsusf_acc_LEUPOLDMK4_2";
this addPrimaryWeaponItem "rhsusf_acc_harris_bipod";
this addWeapon "hgun_P07_F";
this addHandgunItem "muzzle_snds_L";
this addWeapon "Rangefinder";

comment "Add items";
this linkItem "ItemMap";
this linkItem "ItemCompass";
this linkItem "ItemWatch";
this linkItem "tf_anprc152_2";
this linkItem "ItemGPS";
this linkItem "NVGoggles";

